### ISSUE TITLE
Set up MinIO

### ISSUE THREAD

**Issue by paseaf** [paseaf/ContainerSSH-honeypot#3]
## Goal
Create a VM for MinIO and run MinIO container after the VM is deployed.

> Furthermore, you will need an S3-compatible object storage to upload [audit logs](https://containerssh.io/reference/audit/) and we will need a [Prometheus](https://prometheus.io/) installation for monitoring.

Background
MinIO is an S3-compatible server (provides a standardized API for managing objects) that supports different types of storage systems. We use MinIO for the service and local disk drive for persistence.

## Subtasks
- [x] Preparation steps
  -  Learn more about MinIO container.
  - Decide how to host it.
- [x] Create an image for logger ~preinstalled with MinIO container~
~You don't install container!~
- [x] Set up the VM with terraform
- [x] Run MinIO after VM is provisioned
Terraform Provisioners or Ansible?
- [ ] (Maybe) connect it with other VMs

## Design decisions
Why MinIO: 
- ~Google Cloud Storage is not S3 compatible ([source](https://www.ibm.com/support/pages/using-google-cloud-storage-s3-advanced-storage-device-content-platform-engine#:~:text=Google%20Object%20Storage%20provides%20a,through%20an%20S3%2Dcompatible%20API.))~
- Seems like a popular S3-compatible storage, and it's also used in [ContainerSSH test code](https://github.com/ContainerSSH/libcontainerssh/blob/main/internal/test/s3.go#L35)
### Deployment mode: Standalone
There are two deployment modes for MinIO : Standalone and Distributed.
We use standalone for simplicity. 
For production we should consider distributed mode as it provides more stability and scalability.

To learn more about their difference, read [MinIO - Deployment and Management](https://docs.min.io/minio/baremetal/installation/deployment-and-management.html).

### Store files _locally_ on MinIO's host machine
As recommended by [MinIO docs](https://docs.min.io/minio/baremetal/reference/minio-server/minio-server.html#minio.server.DIRECTORIES)
> MinIO recommends locally-attached drives [...]. MinIO recommends against using network-attached storage, as network latency reduces performance of those drives compared to locally-attached storage.

### Host it with Compute Instance over Cloud Run
Q: Host it in a VM or in kubernetes, or some GCP's container runtime env? Should it be running 24/7 or only upon request?
Seems it's easier to set it up in VMs over in containers.
VM provides local persistent storage & 24/7 standby (avoid cold start latency) automatically, which benefits MinIO.

## Relevant readings
- MinIO Deployment requirements: https://blog.min.io/best-practices-minio-virtualized/
  - MinIO is network bound
